Forms
Chris-Costa/Project pull request #4
Opened 2022-08-10 19:43 UTC by Chris-Costa

-Changes to general layout of app adding guards for two tabs when user is not auth.
-Added to existing exercise list component to create new workouts.  This data is sent to new component workout list and is displayed on its own page. 
-Added a profile editing component for first and last name as well as avatar for gender of user.  
-Basic blog component and form for new posts.
-Other angular material styling updates

2022-08-23 21:03 UTC, swhook52 requested changes
I think i'm only through about half but I ran out of time.

2022-08-23 21:03 UTC, swhook52 commented on cvFit/src/app/exercises/workoutList/dataTransfer.service.ts
> +export class TransferService {
This is another one where I'm not sure what it's doing. This looks like a service to share data with other components? The variables and actions could be better with some renames. Then maybe when we understand what it's doing we might not even have a need for the service at all.

2022-08-24 13:18 UTC, Chris-Costa commented on cvFit/src/app/exercises/exercise-list.component.ts
> +    bool: boolean = true;
renamed these and added some comments to this file.  also pulled all variables to the top

2022-08-24 13:39 UTC, Chris-Costa commented on cvFit/src/app/blog/blog.component.ts
> +    filteredList: IBlogPost[] = [
that makes sense.  I was thinking about this with the workout list as well.  Something like that should also reference the user id

2022-08-24 14:16 UTC, Chris-Costa commented on cvFit/src/app/blog/blog.component.html
> +          <mat-card-title><a id="exerName" [routerLink]="['/discussion', blogPost.blogId]">
I'm confused about this comment.  Currently this routerLink works as intended and will expand the details of each unique blog post.  I also have this code in the exercise list -> exercise detail components.

2022-08-24 14:53 UTC, Chris-Costa commented on cvFit/src/app/blog/discussion/discussion.component.ts
> +    holdId: number;
renamed to commentsBlogId (still feel like this name is a bit confusing), using this variable to give an id to the comments.  In the html if this comment id and id of the blogPost match the comment belongs to that blog post and should be displayed when details of the post are expanded.

2022-08-24 17:43 UTC, Chris-Costa commented on cvFit/src/app/app.component.ts
> +    this.auth.logout().subscribe(() => {
used a take(1)

2022-08-31 17:38 UTC, Chris-Costa commented on cvFit/src/app/blog/blog.component.html
> +          <mat-card-title><a id="exerName" [routerLink]="['/discussion', blogPost.blogId]">
I ended up changing this code anyways.  The routerLink portion has been replaced with a (click) event that receives the Id

2022-08-31 17:40 UTC, Chris-Costa commented on cvFit/src/app/blog/discussion/discussion.component.ts
> +        this.blogService.getBlogPost(id).subscribe({
using async here

2022-08-31 20:58 UTC, Chris-Costa commented
Changes made based on the comments.  Still need to work through getting a complete list of liked blog posts(currently hardcoded to produce one post).  Will be working to fix similar observable issues that are present in other files that aren't a part of the previous review (exercise list and exercise details).  Let me about the dataTransfer service and best ways to move forward with that code.

2022-09-02 13:49 UTC, swhook52 approved these changes

2022-09-02 13:49 UTC, merged